Improved the multi_dimensional_lstm_test code and pinpointed what seem to be at least two bugs: 1. the packing code seemingly collects results from the wrong examples 2. It also seems to completely wrongly compute the second example with two    simple examples in a list, since both activations should be the same    since both are the same examples
"

The inputs:

  input_tensor = torch.ones(2, 1, 2, 2).cuda()
  input_tensor_list = list([torch.ones(1, 2, 2).cuda(), torch.ones(1, 2, 2).cuda()])

The results:

 - without packing:
tensor(1.00000e-02 *
       [[[-5.8263, -7.2274],
         [-7.8698, -7.2462]]], device='cuda:0')
 - with packing:
tensor(1.00000e-02 *
       [[[[-5.8263, -7.2274],
          [-7.5380, -5.4770]]]], device='cuda:0')

activations): tensor(1.00000e-02 *
       [[[[-5.8263, -7.2274,  0.0000],   <==== OK
          [-0.0000, -7.8698, -7.2462],   <=== OK but not properly selected
          [-0.0000, -0.0000, -0.0000],
          [-7.9043, -8.0605, -0.0000],          # Wrong
          [-0.0000, -7.5380, -5.4770]]]], device='cuda:0')  # Wrong, wrongly selected

untimeError: Error: expected the same activations for MDLSTM forward computationwith or without packing, but got different results:
 - without packing:
tensor(1.00000e-02 *
       [[[-5.8263, -7.2274],
         [-7.8698, -7.2462]]], device='cuda:0')
 - with packing:
tensor(1.00000e-02 *
       [[[[-5.8263, -7.2274],
          [-7.5380, -5.4770]]]], device='cuda:0')

"